/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoleRouteImport } from './routes/role'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.$role'
import { Route as AuthRoleRouteImport } from './routes/auth.$role'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin.unauthorized'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppEarningsRouteImport } from './routes/_app.earnings'
import { Route as AppCoverageRouteImport } from './routes/_app.coverage'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as ApiPublicMonnifyWebhookRouteImport } from './routes/api/public/monnify-webhook'
import { Route as AdminAdminVerificationRouteImport } from './routes/_admin.admin.verification'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminUnpaidRouteImport } from './routes/_admin.admin.unpaid'
import { Route as AdminAdminSystemRouteImport } from './routes/_admin.admin.system'
import { Route as AdminAdminSupportRouteImport } from './routes/_admin.admin.support'
import { Route as AdminAdminShiftsRouteImport } from './routes/_admin.admin.shifts'
import { Route as AdminAdminRiskRouteImport } from './routes/_admin.admin.risk'
import { Route as AdminAdminRequestersRouteImport } from './routes/_admin.admin.requesters'
import { Route as AdminAdminFlashboardRouteImport } from './routes/_admin.admin.flashboard'
import { Route as AdminAdminFinanceRouteImport } from './routes/_admin.admin.finance'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/$role',
  path: '/onboarding/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/$role',
  path: '/auth/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/admin/unauthorized',
  path: '/admin/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppCoverageRoute = AppCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const ApiPublicMonnifyWebhookRoute = ApiPublicMonnifyWebhookRouteImport.update({
  id: '/api/public/monnify-webhook',
  path: '/api/public/monnify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminVerificationRoute = AdminAdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUnpaidRoute = AdminAdminUnpaidRouteImport.update({
  id: '/unpaid',
  path: '/unpaid',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSystemRoute = AdminAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSupportRoute = AdminAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminShiftsRoute = AdminAdminShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRiskRoute = AdminAdminRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRequestersRoute = AdminAdminRequestersRouteImport.update({
  id: '/requesters',
  path: '/requesters',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFlashboardRoute = AdminAdminFlashboardRouteImport.update({
  id: '/flashboard',
  path: '/flashboard',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFinanceRoute = AdminAdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminAdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role': typeof RoleRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/account': typeof AppAccountRoute
  '/coverage': typeof AppCoverageRoute
  '/earnings': typeof AppEarningsRoute
  '/home': typeof AppHomeRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/auth/$role': typeof AuthRoleRoute
  '/onboarding/$role': typeof OnboardingRoleRoute
  '/admin/finance': typeof AdminAdminFinanceRoute
  '/admin/flashboard': typeof AdminAdminFlashboardRoute
  '/admin/requesters': typeof AdminAdminRequestersRoute
  '/admin/risk': typeof AdminAdminRiskRoute
  '/admin/shifts': typeof AdminAdminShiftsRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/system': typeof AdminAdminSystemRoute
  '/admin/unpaid': typeof AdminAdminUnpaidRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/verification': typeof AdminAdminVerificationRoute
  '/api/public/monnify-webhook': typeof ApiPublicMonnifyWebhookRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role': typeof RoleRoute
  '/account': typeof AppAccountRoute
  '/coverage': typeof AppCoverageRoute
  '/earnings': typeof AppEarningsRoute
  '/home': typeof AppHomeRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/auth/$role': typeof AuthRoleRoute
  '/onboarding/$role': typeof OnboardingRoleRoute
  '/admin/finance': typeof AdminAdminFinanceRoute
  '/admin/flashboard': typeof AdminAdminFlashboardRoute
  '/admin/requesters': typeof AdminAdminRequestersRoute
  '/admin/risk': typeof AdminAdminRiskRoute
  '/admin/shifts': typeof AdminAdminShiftsRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/system': typeof AdminAdminSystemRoute
  '/admin/unpaid': typeof AdminAdminUnpaidRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/verification': typeof AdminAdminVerificationRoute
  '/api/public/monnify-webhook': typeof ApiPublicMonnifyWebhookRoute
  '/admin': typeof AdminAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/role': typeof RoleRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/coverage': typeof AppCoverageRoute
  '/_app/earnings': typeof AppEarningsRoute
  '/_app/home': typeof AppHomeRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/auth/$role': typeof AuthRoleRoute
  '/onboarding/$role': typeof OnboardingRoleRoute
  '/_admin/admin/finance': typeof AdminAdminFinanceRoute
  '/_admin/admin/flashboard': typeof AdminAdminFlashboardRoute
  '/_admin/admin/requesters': typeof AdminAdminRequestersRoute
  '/_admin/admin/risk': typeof AdminAdminRiskRoute
  '/_admin/admin/shifts': typeof AdminAdminShiftsRoute
  '/_admin/admin/support': typeof AdminAdminSupportRoute
  '/_admin/admin/system': typeof AdminAdminSystemRoute
  '/_admin/admin/unpaid': typeof AdminAdminUnpaidRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/verification': typeof AdminAdminVerificationRoute
  '/api/public/monnify-webhook': typeof ApiPublicMonnifyWebhookRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/role'
    | '/admin'
    | '/account'
    | '/coverage'
    | '/earnings'
    | '/home'
    | '/admin/unauthorized'
    | '/auth/$role'
    | '/onboarding/$role'
    | '/admin/finance'
    | '/admin/flashboard'
    | '/admin/requesters'
    | '/admin/risk'
    | '/admin/shifts'
    | '/admin/support'
    | '/admin/system'
    | '/admin/unpaid'
    | '/admin/users'
    | '/admin/verification'
    | '/api/public/monnify-webhook'
    | '/admin/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/role'
    | '/account'
    | '/coverage'
    | '/earnings'
    | '/home'
    | '/admin/unauthorized'
    | '/auth/$role'
    | '/onboarding/$role'
    | '/admin/finance'
    | '/admin/flashboard'
    | '/admin/requesters'
    | '/admin/risk'
    | '/admin/shifts'
    | '/admin/support'
    | '/admin/system'
    | '/admin/unpaid'
    | '/admin/users'
    | '/admin/verification'
    | '/api/public/monnify-webhook'
    | '/admin'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/reset-password'
    | '/role'
    | '/_admin/admin'
    | '/_app/account'
    | '/_app/coverage'
    | '/_app/earnings'
    | '/_app/home'
    | '/admin/unauthorized'
    | '/auth/$role'
    | '/onboarding/$role'
    | '/_admin/admin/finance'
    | '/_admin/admin/flashboard'
    | '/_admin/admin/requesters'
    | '/_admin/admin/risk'
    | '/_admin/admin/shifts'
    | '/_admin/admin/support'
    | '/_admin/admin/system'
    | '/_admin/admin/unpaid'
    | '/_admin/admin/users'
    | '/_admin/admin/verification'
    | '/api/public/monnify-webhook'
    | '/_admin/admin/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoleRoute: typeof RoleRoute
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  AuthRoleRoute: typeof AuthRoleRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  ApiPublicMonnifyWebhookRoute: typeof ApiPublicMonnifyWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$role': {
      id: '/onboarding/$role'
      path: '/onboarding/$role'
      fullPath: '/onboarding/$role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$role': {
      id: '/auth/$role'
      path: '/auth/$role'
      fullPath: '/auth/$role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unauthorized': {
      id: '/admin/unauthorized'
      path: '/admin/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/earnings': {
      id: '/_app/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coverage': {
      id: '/_app/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof AppCoverageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/api/public/monnify-webhook': {
      id: '/api/public/monnify-webhook'
      path: '/api/public/monnify-webhook'
      fullPath: '/api/public/monnify-webhook'
      preLoaderRoute: typeof ApiPublicMonnifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/verification': {
      id: '/_admin/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminAdminVerificationRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/unpaid': {
      id: '/_admin/admin/unpaid'
      path: '/unpaid'
      fullPath: '/admin/unpaid'
      preLoaderRoute: typeof AdminAdminUnpaidRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/system': {
      id: '/_admin/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminAdminSystemRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/support': {
      id: '/_admin/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminAdminSupportRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/shifts': {
      id: '/_admin/admin/shifts'
      path: '/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AdminAdminShiftsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/risk': {
      id: '/_admin/admin/risk'
      path: '/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AdminAdminRiskRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/requesters': {
      id: '/_admin/admin/requesters'
      path: '/requesters'
      fullPath: '/admin/requesters'
      preLoaderRoute: typeof AdminAdminRequestersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/flashboard': {
      id: '/_admin/admin/flashboard'
      path: '/flashboard'
      fullPath: '/admin/flashboard'
      preLoaderRoute: typeof AdminAdminFlashboardRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/finance': {
      id: '/_admin/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminAdminFinanceRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminFinanceRoute: typeof AdminAdminFinanceRoute
  AdminAdminFlashboardRoute: typeof AdminAdminFlashboardRoute
  AdminAdminRequestersRoute: typeof AdminAdminRequestersRoute
  AdminAdminRiskRoute: typeof AdminAdminRiskRoute
  AdminAdminShiftsRoute: typeof AdminAdminShiftsRoute
  AdminAdminSupportRoute: typeof AdminAdminSupportRoute
  AdminAdminSystemRoute: typeof AdminAdminSystemRoute
  AdminAdminUnpaidRoute: typeof AdminAdminUnpaidRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminVerificationRoute: typeof AdminAdminVerificationRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminFinanceRoute: AdminAdminFinanceRoute,
  AdminAdminFlashboardRoute: AdminAdminFlashboardRoute,
  AdminAdminRequestersRoute: AdminAdminRequestersRoute,
  AdminAdminRiskRoute: AdminAdminRiskRoute,
  AdminAdminShiftsRoute: AdminAdminShiftsRoute,
  AdminAdminSupportRoute: AdminAdminSupportRoute,
  AdminAdminSystemRoute: AdminAdminSystemRoute,
  AdminAdminUnpaidRoute: AdminAdminUnpaidRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminVerificationRoute: AdminAdminVerificationRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCoverageRoute: typeof AppCoverageRoute
  AppEarningsRoute: typeof AppEarningsRoute
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCoverageRoute: AppCoverageRoute,
  AppEarningsRoute: AppEarningsRoute,
  AppHomeRoute: AppHomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RoleRoute: RoleRoute,
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  AuthRoleRoute: AuthRoleRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  ApiPublicMonnifyWebhookRoute: ApiPublicMonnifyWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
