/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoleRouteImport } from './routes/role'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRoleRouteImport } from './routes/auth.$role'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppEarningsRouteImport } from './routes/_app.earnings'
import { Route as AppCoverageRouteImport } from './routes/_app.coverage'
import { Route as AppAccountRouteImport } from './routes/_app.account'

const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/$role',
  path: '/auth/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppCoverageRoute = AppCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/role': typeof RoleRoute
  '/account': typeof AppAccountRoute
  '/coverage': typeof AppCoverageRoute
  '/earnings': typeof AppEarningsRoute
  '/home': typeof AppHomeRoute
  '/auth/$role': typeof AuthRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/role': typeof RoleRoute
  '/account': typeof AppAccountRoute
  '/coverage': typeof AppCoverageRoute
  '/earnings': typeof AppEarningsRoute
  '/home': typeof AppHomeRoute
  '/auth/$role': typeof AuthRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/role': typeof RoleRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/coverage': typeof AppCoverageRoute
  '/_app/earnings': typeof AppEarningsRoute
  '/_app/home': typeof AppHomeRoute
  '/auth/$role': typeof AuthRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/role'
    | '/account'
    | '/coverage'
    | '/earnings'
    | '/home'
    | '/auth/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/role'
    | '/account'
    | '/coverage'
    | '/earnings'
    | '/home'
    | '/auth/$role'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/role'
    | '/_app/account'
    | '/_app/coverage'
    | '/_app/earnings'
    | '/_app/home'
    | '/auth/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RoleRoute: typeof RoleRoute
  AuthRoleRoute: typeof AuthRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$role': {
      id: '/auth/$role'
      path: '/auth/$role'
      fullPath: '/auth/$role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/earnings': {
      id: '/_app/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coverage': {
      id: '/_app/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof AppCoverageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCoverageRoute: typeof AppCoverageRoute
  AppEarningsRoute: typeof AppEarningsRoute
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCoverageRoute: AppCoverageRoute,
  AppEarningsRoute: AppEarningsRoute,
  AppHomeRoute: AppHomeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RoleRoute: RoleRoute,
  AuthRoleRoute: AuthRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
